name: Tests

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  tests-linux:
    name: Tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/ -s

  tests-windows:
    name: Tests on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip

    - name: Install requirements
      shell: bash           # ← make Unix-style commands work on Windows
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      shell: bash
      run: pytest tests/ -s